name: Create Release

on:
  push:
    branches:
      - main

jobs:
  # Build APK job
  build:
    uses: ./.github/workflows/build.yml

  # Tag and release job
  tag-and-release:
    needs: build
    uses: ./.github/workflows/tag-and-release.yml
    with:
      version: ${{ needs.build.outputs.version }}
      apk_path: ${{ needs.build.outputs.apk_path }}
      apk_name: ${{ needs.build.outputs.apk_name }}
    secrets: inherit
